services:
  - type: web
    name: tabbycat_website
    env: python
    autoDeployTrigger: off
    plan: free
    region: oregon
    buildCommand: "./bin/render-compile.sh"
    startCommand: "npm run render-serve"
    envVars:
      - key: DATABASE_URL
        sync: false # Managed by the guarded Render rotation workflow
      - key: REDIS_HOST
        fromService:
          type: redis
          name: tabbycat_redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: tabbycat_redis
          property: port
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: WEB_CONCURRENCY
        value: 4
      - key: TAB_DIRECTOR_EMAIL
        sync: false
      - key: DEBSOC_MEMBERS_CSV_URL
        value: "https://docs.google.com/spreadsheets/d/1HuvRJgz1w3Rs3HFhHgj99W3JhJJEUyDmTKo8tXzHNmc/export?format=csv"
      - key: DEBSOC_EMAIL_DELAY
        value: 1
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: TIME_ZONE
        sync: false
      - key: ON_RENDER
        value: true
      - key: USING_NGINX
        value: 0 # Not 'false'; is cast
  - type: redis
    name: tabbycat_redis
    ipAllowList: # required
      - source: 0.0.0.0
        description: everywhere
    plan: free
    maxmemoryPolicy: allkeys-lru # (default)
